import { Releases } from "@/types/GithubApi"

export const githubApiResponse: Releases = [
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/86888694",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/86888694/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/86888694/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.6.1",
    id: 86888694,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "RE_kwDOEYN9hs4FLdD2",
    tag_name: "3.6.1",
    target_commitish: "main",
    name: "Add Lifestyles",
    draft: false,
    prerelease: false,
    created_at: "2022-12-22T05:28:27Z",
    published_at: "2022-12-22T05:31:05Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.6.1",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.6.1",
    body: "* added lifestyles to buy and sell...\r\n* made resource summary columns uniform, to make it look nice\r\n* fixed links to magic gear and security gear when linked from resource summary",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/84933030",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/84933030/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/84933030/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.6.0",
    id: 84933030,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "RE_kwDOEYN9hs4FD_mm",
    tag_name: "3.6.0",
    target_commitish: "main",
    name: "Analytics",
    draft: false,
    prerelease: false,
    created_at: "2022-12-05T00:29:08Z",
    published_at: "2022-12-05T00:33:48Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.6.0",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.6.0",
    body: "Vercel has some kind of new analytics package, and I want to checkout what it can do. Also I guess it might be nice to see how many people actually use this app.",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/84896270",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/84896270/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/84896270/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.5.4",
    id: 84896270,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "RE_kwDOEYN9hs4FD2oO",
    tag_name: "3.5.4",
    target_commitish: "main",
    name: "Add Gear Summary to the Resource page",
    draft: false,
    prerelease: false,
    created_at: "2022-12-03T20:20:50Z",
    published_at: "2022-12-03T20:25:46Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.5.4",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.5.4",
    body: "All the gear a runner has will appear on the resource page. The headers are links to the resource if you want to modify them.\r\n\r\nUpdated a lot of things under the hood. Hopefully there shouldn't be many changes to the end user. But upgrading to the newest version of Next broke some styling with Material UI. But it should all still function.\r\n\r\nI forked and updated react-indexed-db to remove its security vulnerabilities. This actually doesn't effect the end user, it was only a problem that dependebot was yelling at me about.",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/77348745",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/77348745/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/77348745/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.5.3",
    id: 77348745,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "RE_kwDOEYN9hs4EnD-J",
    tag_name: "3.5.3",
    target_commitish: "main",
    name: "Add audio and vision cyberware",
    draft: false,
    prerelease: false,
    created_at: "2022-09-16T00:58:55Z",
    published_at: "2022-09-16T01:00:52Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.5.3",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.5.3",
    body: "",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/76851379",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/76851379/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/76851379/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.5.2",
    id: 76851379,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "RE_kwDOEYN9hs4ElKiz",
    tag_name: "3.5.2",
    target_commitish: "main",
    name: "Add Cyberware Mod page",
    draft: false,
    prerelease: false,
    created_at: "2022-09-12T03:02:20Z",
    published_at: "2022-09-12T03:04:59Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.5.2",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.5.2",
    body: "",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/74946117",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/74946117/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/74946117/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.5.1",
    id: 74946117,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "RE_kwDOEYN9hs4Ed5ZF",
    tag_name: "3.5.1",
    target_commitish: "main",
    name: "Add Bioware",
    draft: false,
    prerelease: false,
    created_at: "2022-08-22T00:52:25Z",
    published_at: "2022-08-22T00:54:29Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.5.1",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.5.1",
    body: "- fix bug that displayed cyberware that could only be installed in capacity\r\n- removed skill jack duplicate entry\r\n- fixed cybereyes rating 5 essence cost",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/73834490",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/73834490/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/73834490/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.5.0",
    id: 73834490,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "RE_kwDOEYN9hs4EZp_6",
    tag_name: "3.5.0",
    target_commitish: "main",
    name: "Standard Cyberware",
    draft: false,
    prerelease: false,
    created_at: "2022-08-07T14:58:26Z",
    published_at: "2022-08-07T14:59:58Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.5.0",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.5.0",
    body: "Added page to buy standard cyberware",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/71329938",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/71329938/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/71329938/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.4.1",
    id: 71329938,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "RE_kwDOEYN9hs4EQGiS",
    tag_name: "3.4.1",
    target_commitish: "main",
    name: "Add new nightwatch (dark) theme",
    draft: false,
    prerelease: false,
    created_at: "2022-07-06T02:53:32Z",
    published_at: "2022-07-06T03:00:18Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.4.1",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.4.1",
    body: "* added max width on menu to not make it so wide on larger screens\r\n* made a few other small importments to the style",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/68904712",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/68904712/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/68904712/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.4.0",
    id: 68904712,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "RE_kwDOEYN9hs4EG2cI",
    tag_name: "3.4.0",
    target_commitish: "main",
    name: "Theming Style selector",
    draft: false,
    prerelease: false,
    created_at: "2022-06-08T03:17:51Z",
    published_at: "2022-06-08T03:21:00Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.4.0",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.4.0",
    body: "able to toggle between the current awesome style, and a boring and inferior style in the hamburger menu.",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/62855604",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/62855604/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/62855604/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.31",
    id: 62855604,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "RE_kwDOEYN9hs4Dvxm0",
    tag_name: "3.3.31",
    target_commitish: "main",
    name: "Add Armor Mods Page",
    draft: false,
    prerelease: false,
    created_at: "2022-03-27T00:55:31Z",
    published_at: "2022-03-27T01:03:25Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.31",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.31",
    body: "",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/60195076",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/60195076/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/60195076/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.30",
    id: 60195076,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "RE_kwDOEYN9hs4DloEE",
    tag_name: "3.3.30",
    target_commitish: "main",
    name: "Add Firearm Mods",
    draft: false,
    prerelease: false,
    created_at: "2022-02-23T05:13:22Z",
    published_at: "2022-02-23T05:20:58Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.30",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.30",
    body: "",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/50174353",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/50174353/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/50174353/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.29",
    id: 50174353,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "RE_kwDOEYN9hs4C_ZmR",
    tag_name: "3.3.29",
    target_commitish: "main",
    name: "Drone and Vehicle modding",
    draft: false,
    prerelease: false,
    created_at: "2021-09-24T00:30:51Z",
    published_at: "2021-09-24T00:38:50Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.29",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.29",
    body: "Added sub page to mod drones and vehicles",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/48601289",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/48601289/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/48601289/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.28",
    id: 48601289,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQ4NjAxMjg5",
    tag_name: "3.3.28",
    target_commitish: "main",
    name: "Vehicles!",
    draft: false,
    prerelease: false,
    created_at: "2021-08-27T23:04:48Z",
    published_at: "2021-08-27T23:10:11Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.28",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.28",
    body: "Added Vehicles to buy and sell",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/48227427",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/48227427/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/48227427/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.27",
    id: 48227427,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQ4MjI3NDI3",
    tag_name: "3.3.27",
    target_commitish: "main",
    name: "Drones!",
    draft: false,
    prerelease: false,
    created_at: "2021-08-21T20:08:30Z",
    published_at: "2021-08-21T20:14:29Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.27",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.27",
    body: "Added drones to buy",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/47103723",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/47103723/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/47103723/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.26",
    id: 47103723,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQ3MTAzNzIz",
    tag_name: "3.3.26",
    target_commitish: "main",
    name: "Add Magic Gear",
    draft: false,
    prerelease: false,
    created_at: "2021-08-01T03:38:05Z",
    published_at: "2021-08-01T03:43:24Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.26",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.26",
    body: "Able to now purchase\r\n\r\n- foci\r\n- magic lodge stuff\r\n- Reagents\r\n- formuli",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/45586770",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/45586770/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/45586770/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.25",
    id: 45586770,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQ1NTg2Nzcw",
    tag_name: "3.3.25",
    target_commitish: "main",
    name: "Biotech added",
    draft: false,
    prerelease: false,
    created_at: "2021-07-01T20:30:07Z",
    published_at: "2021-07-01T20:40:17Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.25",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.25",
    body: "Biotech gear has been added.",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/45211399",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/45211399/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/45211399/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.24",
    id: 45211399,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQ1MjExMzk5",
    tag_name: "3.3.24",
    target_commitish: "main",
    name: "All security gear, drugs, and toxins",
    draft: false,
    prerelease: false,
    created_at: "2021-06-25T03:27:51Z",
    published_at: "2021-06-25T03:33:58Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.24",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.24",
    body: "Gear added\r\n- locks\r\n- restraints\r\n- bne\r\n- chemicals\r\n- survival\r\n- grappleGun\r\n- toxins\r\n- drugs",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/43811451",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/43811451/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/43811451/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.23",
    id: 43811451,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQzODExNDUx",
    tag_name: "3.3.23",
    target_commitish: "main",
    name: "Restraints",
    draft: false,
    prerelease: false,
    created_at: "2021-05-30T00:50:00Z",
    published_at: "2021-05-30T00:52:18Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.23",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.23",
    body: "",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/43440946",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/43440946/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/43440946/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.22",
    id: 43440946,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQzNDQwOTQ2",
    tag_name: "3.3.22",
    target_commitish: "main",
    name: "Locks",
    draft: false,
    prerelease: false,
    created_at: "2021-05-24T02:30:04Z",
    published_at: "2021-05-24T02:34:40Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.22",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.22",
    body: "",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/41682731",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/41682731/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/41682731/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.21",
    id: 41682731,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQxNjgyNzMx",
    tag_name: "3.3.21",
    target_commitish: "main",
    name: "Added Sensors!",
    draft: false,
    prerelease: false,
    created_at: "2021-04-20T02:46:40Z",
    published_at: "2021-04-20T03:19:50Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.21",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.21",
    body: "",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/41595040",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/41595040/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/41595040/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.20",
    id: 41595040,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQxNTk1MDQw",
    tag_name: "3.3.20",
    target_commitish: "main",
    name: "Added Audio Mod page",
    draft: false,
    prerelease: false,
    created_at: "2021-04-17T22:34:48Z",
    published_at: "2021-04-17T22:39:00Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.20",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.20",
    body: "I can't believe I forgot to make this page but made everything else...",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/41594853",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/41594853/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/41594853/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.19",
    id: 41594853,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQxNTk0ODUz",
    tag_name: "3.3.19",
    target_commitish: "main",
    name: "Audio mods added",
    draft: false,
    prerelease: false,
    created_at: "2021-04-17T22:24:13Z",
    published_at: "2021-04-17T22:26:39Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.19",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.19",
    body: "",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/41591981",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/41591981/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/41591981/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.18",
    id: 41591981,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQxNTkxOTgx",
    tag_name: "3.3.18",
    target_commitish: "main",
    name: "Audio device page added",
    draft: false,
    prerelease: false,
    created_at: "2021-04-17T19:21:33Z",
    published_at: "2021-04-17T19:28:21Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.18",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.18",
    body: "",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/41578019",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/41578019/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/41578019/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.17",
    id: 41578019,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQxNTc4MDE5",
    tag_name: "3.3.17",
    target_commitish: "main",
    name: "Non moddable imaging devices added",
    draft: false,
    prerelease: false,
    created_at: "2021-04-17T03:26:39Z",
    published_at: "2021-04-17T03:29:00Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.17",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.17",
    body: "",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/41494603",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/41494603/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/41494603/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.16",
    id: 41494603,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQxNDk0NjAz",
    tag_name: "3.3.16",
    target_commitish: "main",
    name: "Ability to modify Imaging Devices",
    draft: false,
    prerelease: false,
    created_at: "2021-04-15T16:20:55Z",
    published_at: "2021-04-15T16:25:16Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.16",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.16",
    body: "",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/41241506",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/41241506/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/41241506/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.15",
    id: 41241506,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTQxMjQxNTA2",
    tag_name: "3.3.15",
    target_commitish: "main",
    name: "Nothing really important...",
    draft: false,
    prerelease: false,
    created_at: "2021-04-11T14:41:34Z",
    published_at: "2021-04-11T14:51:06Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.15",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.15",
    body: "* updated breadcrumbs on resource page to allow one level more nested paths\r\n* tried another fix to allow vercel to not 404 on refresh...didn't work\r\n* fixed some webpack 5 build errors",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/39284487",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/39284487/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/39284487/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.14",
    id: 39284487,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTM5Mjg0NDg3",
    tag_name: "3.3.14",
    target_commitish: "main",
    name: "Tools",
    draft: false,
    prerelease: false,
    created_at: "2021-03-04T15:48:09Z",
    published_at: "2021-03-04T15:50:16Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.14",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.14",
    body: "* Added the ability to buy tools and associated them with an active skill\r\n* fix bug that allowed selecting invalid metatypes based off priority rating",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/37901164",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/37901164/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/37901164/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.13",
    id: 37901164,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTM3OTAxMTY0",
    tag_name: "3.3.13",
    target_commitish: "main",
    name: "Add Fake SIN and Lisences",
    draft: false,
    prerelease: false,
    created_at: "2021-02-11T05:00:28Z",
    published_at: "2021-02-11T05:01:54Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.13",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.13",
    body: "* fix deployment to prod\r\n* also added fake SINs and licenses",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/37810554",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/37810554/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/37810554/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.12",
    id: 37810554,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTM3ODEwNTU0",
    tag_name: "3.3.12",
    target_commitish: "main",
    name: "Other Electronics",
    draft: false,
    prerelease: false,
    created_at: "2021-02-09T16:16:26Z",
    published_at: "2021-02-09T16:21:06Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.12",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.12",
    body: "* Added other electronics\r\n  * Communications\r\n  * Credsticks\r\n* Added ability to purchase gear at different ratings",
  },
  {
    url: "https://api.github.com/repos/HeyOmae/OMA3/releases/36745227",
    assets_url:
      "https://api.github.com/repos/HeyOmae/OMA3/releases/36745227/assets",
    upload_url:
      "https://uploads.github.com/repos/HeyOmae/OMA3/releases/36745227/assets{?name,label}",
    html_url: "https://github.com/HeyOmae/OMA3/releases/tag/3.3.11",
    id: 36745227,
    author: {
      login: "dethstrobe",
      id: 6279187,
      node_id: "MDQ6VXNlcjYyNzkxODc=",
      avatar_url: "https://avatars.githubusercontent.com/u/6279187?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/dethstrobe",
      html_url: "https://github.com/dethstrobe",
      followers_url: "https://api.github.com/users/dethstrobe/followers",
      following_url:
        "https://api.github.com/users/dethstrobe/following{/other_user}",
      gists_url: "https://api.github.com/users/dethstrobe/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/dethstrobe/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/dethstrobe/subscriptions",
      organizations_url: "https://api.github.com/users/dethstrobe/orgs",
      repos_url: "https://api.github.com/users/dethstrobe/repos",
      events_url: "https://api.github.com/users/dethstrobe/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/dethstrobe/received_events",
      type: "User",
      site_admin: false,
    },
    node_id: "MDc6UmVsZWFzZTM2NzQ1MjI3",
    tag_name: "3.3.11",
    target_commitish: "main",
    name: "RFID Tags",
    draft: false,
    prerelease: false,
    created_at: "2021-01-22T01:43:36Z",
    published_at: "2021-01-22T01:46:09Z",
    assets: [],
    tarball_url: "https://api.github.com/repos/HeyOmae/OMA3/tarball/3.3.11",
    zipball_url: "https://api.github.com/repos/HeyOmae/OMA3/zipball/3.3.11",
    body: "",
  },
]
